[package]
name = "maki-storage"
version.workspace = true
edition.workspace = true

[dependencies]
maki-domain = { workspace = true }
getrandom = { workspace = true }
isahc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
fs2 = { workspace = true }
fs4 = { workspace = true }
etcetera = { workspace = true }
bs58 = { workspace = true }
uuid = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs", "std"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Wdk_Foundation", "Wdk_Storage_FileSystem", "Win32_Security", "Win32_Storage_FileSystem", "Win32_System_IO"] }

[dev-dependencies]
flume = { workspace = true }
smol = { workspace = true }
test-case = { workspace = true }
tempfile = { workspace = true }
isahc = { workspace = true }
serde_json = { workspace = true }
