base_url = "/docs"
title = "Makima Docs"
compile_sass = true
build_search_index = false

[markdown.highlighting]
enabled = true
style = "inline"
theme = "lunared"
extra_themes = ["extra/lunared.json"]
